class Main {
  public static void main(String[] args) {
    
    double a=7;
    double b=3;
    //int x=a/b;
    double y=a/b;
    //int y=a%b; modulo operator(remainder)
    //System.out.println("integer"+x);
    System.out.println("double value"+y);
    System.out.println(a>b);
    System.out.println(a==b);
    System.out.println(a!=b);
    System.out.println(a<=b);
    System.out.println(a>=b);
  }
}
